export const SET_CONTACTS_REQUESTED = 'CONTACTS_MANAGER/CONTACTS/REQUESTED'
export const SET_CONTACTS_SUCCEEDED = 'CONTACTS_MANAGER/CONTACTS/SUCCEEDED'
export const SET_CONTACTS_FAILED = 'CONTACTS_MANAGER/CONTACTS/FAILED'
