export const SET_CONTACTS_REQUESTED = 'CONTACTS_MANAGER/CONTACTS/REQUESTED'
export const SET_CONTACTS_SUCCEEDED = 'CONTACTS_MANAGER/CONTACTS/SUCCEEDED'
export const SET_CONTACTS_FAILED = 'CONTACTS_MANAGER/CONTACTS/FAILED'

export const ADD_CONTACT_TO_STORE = 'CONTACTS_MANAGER/ADD_CONTACT/TO_STORE'
export const ADD_CONTACT_SUCCEEDED = 'CONTACTS_MANAGER/ADD_CONTACT/SUCCEEDED'
export const ADD_CONTACT_FAILED = 'CONTACTS_MANAGER/ADD_CONTACT/FAILED'
